// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/ft.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownloadRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d4664f3662ff76d, []int{0}
}

func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(m, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type DownloadResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadResponse) Reset()         { *m = DownloadResponse{} }
func (m *DownloadResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadResponse) ProtoMessage()    {}
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d4664f3662ff76d, []int{1}
}

func (m *DownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResponse.Unmarshal(m, b)
}
func (m *DownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResponse.Marshal(b, m, deterministic)
}
func (m *DownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResponse.Merge(m, src)
}
func (m *DownloadResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadResponse.Size(m)
}
func (m *DownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResponse proto.InternalMessageInfo

func (m *DownloadResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type UploadRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d4664f3662ff76d, []int{2}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *UploadRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type UploadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d4664f3662ff76d, []int{3}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DownloadRequest)(nil), "DownloadRequest")
	proto.RegisterType((*DownloadResponse)(nil), "DownloadResponse")
	proto.RegisterType((*UploadRequest)(nil), "UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "UploadResponse")
}

func init() { proto.RegisterFile("service/ft.proto", fileDescriptor_0d4664f3662ff76d) }

var fileDescriptor_0d4664f3662ff76d = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x37, 0xab, 0x6c, 0xed, 0xa0, 0x69, 0xcc, 0xa9, 0xf4, 0x24, 0x01, 0xa1, 0x07, 0x8d,
	0x62, 0x4f, 0x5e, 0x45, 0xfc, 0x01, 0x45, 0x2f, 0xde, 0x6a, 0x9d, 0x42, 0xa1, 0x66, 0x6a, 0x32,
	0xea, 0xdf, 0x17, 0xfa, 0xc1, 0xb6, 0xbd, 0xcd, 0xc0, 0xfb, 0xf1, 0xf0, 0x82, 0x0a, 0xe8, 0x7f,
	0xdb, 0x1a, 0xef, 0x1a, 0xb6, 0xbd, 0x27, 0x26, 0x73, 0x0d, 0xc9, 0x33, 0xfd, 0xb9, 0x8e, 0xaa,
	0xcf, 0x12, 0xbf, 0x7f, 0x30, 0xb0, 0xd6, 0x70, 0xda, 0x78, 0xfa, 0x4a, 0xc5, 0x95, 0xc8, 0xe3,
	0x72, 0xb8, 0xcd, 0x0d, 0xa8, 0xa3, 0x2c, 0xf4, 0xe4, 0x02, 0xea, 0x14, 0xa2, 0x9a, 0x1c, 0xa3,
	0xe3, 0x41, 0x7a, 0x5e, 0xce, 0xaf, 0x79, 0x84, 0x8b, 0xb7, 0x7e, 0x19, 0x29, 0x61, 0xcf, 0x34,
	0x05, 0xee, 0x99, 0x96, 0xd6, 0x93, 0xb5, 0x55, 0x81, 0x9c, 0xad, 0x63, 0xcd, 0x03, 0x83, 0x7c,
	0x69, 0x3b, 0x7c, 0xf5, 0x95, 0x0b, 0x0d, 0x7a, 0xf4, 0xba, 0x80, 0xb3, 0x19, 0x46, 0x2b, 0xbb,
	0xc1, 0xcf, 0x2e, 0xed, 0x96, 0xd4, 0xec, 0xee, 0x85, 0xbe, 0x85, 0xc3, 0x18, 0xac, 0xa5, 0x5d,
	0xc1, 0x65, 0x89, 0x5d, 0x37, 0x9a, 0x5d, 0x2e, 0x9e, 0xe2, 0xf7, 0x68, 0xda, 0xea, 0xe3, 0x30,
	0x2c, 0x55, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x74, 0x45, 0xee, 0x0f, 0x3d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileTransfererClient is the client API for FileTransferer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileTransfererClient interface {
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (FileTransferer_DownloadClient, error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (FileTransferer_UploadClient, error)
}

type fileTransfererClient struct {
	cc *grpc.ClientConn
}

func NewFileTransfererClient(cc *grpc.ClientConn) FileTransfererClient {
	return &fileTransfererClient{cc}
}

func (c *fileTransfererClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (FileTransferer_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FileTransferer_serviceDesc.Streams[0], "/FileTransferer/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileTransfererDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileTransferer_DownloadClient interface {
	Recv() (*DownloadResponse, error)
	grpc.ClientStream
}

type fileTransfererDownloadClient struct {
	grpc.ClientStream
}

func (x *fileTransfererDownloadClient) Recv() (*DownloadResponse, error) {
	m := new(DownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileTransfererClient) Upload(ctx context.Context, opts ...grpc.CallOption) (FileTransferer_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FileTransferer_serviceDesc.Streams[1], "/FileTransferer/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileTransfererUploadClient{stream}
	return x, nil
}

type FileTransferer_UploadClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type fileTransfererUploadClient struct {
	grpc.ClientStream
}

func (x *fileTransfererUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileTransfererUploadClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileTransfererServer is the server API for FileTransferer service.
type FileTransfererServer interface {
	Download(*DownloadRequest, FileTransferer_DownloadServer) error
	Upload(FileTransferer_UploadServer) error
}

// UnimplementedFileTransfererServer can be embedded to have forward compatible implementations.
type UnimplementedFileTransfererServer struct {
}

func (*UnimplementedFileTransfererServer) Download(req *DownloadRequest, srv FileTransferer_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (*UnimplementedFileTransfererServer) Upload(srv FileTransferer_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterFileTransfererServer(s *grpc.Server, srv FileTransfererServer) {
	s.RegisterService(&_FileTransferer_serviceDesc, srv)
}

func _FileTransferer_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileTransfererServer).Download(m, &fileTransfererDownloadServer{stream})
}

type FileTransferer_DownloadServer interface {
	Send(*DownloadResponse) error
	grpc.ServerStream
}

type fileTransfererDownloadServer struct {
	grpc.ServerStream
}

func (x *fileTransfererDownloadServer) Send(m *DownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FileTransferer_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTransfererServer).Upload(&fileTransfererUploadServer{stream})
}

type FileTransferer_UploadServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type fileTransfererUploadServer struct {
	grpc.ServerStream
}

func (x *fileTransfererUploadServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileTransfererUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FileTransferer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FileTransferer",
	HandlerType: (*FileTransfererServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _FileTransferer_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _FileTransferer_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service/ft.proto",
}
